### ISSUE TITLE
Review error:  Username and Password not accepted

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/bioimageio-uploader#103]
I just tried to leave a "request for changes" for https://bioimageio-uploader.netlify.app/#/status/artistic-ladybird and got this error message after entering a message and clicking "Request Changes".
```
                Traceback (most recent call last):

  File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 110, in wrapper
    data = await handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 314, in review
    review_data.save(backoffice)

  File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 77, in save
    backoffice.request_changes(

  File "/home/weiouyang/miniconda3/lib/python3.12/site-packages/bioimageio_collection_backoffice/_backoffice.py", line 147, in request_changes
    notify_uploader(

  File "/home/weiouyang/miniconda3/lib/python3.12/site-packages/bioimageio_collection_backoffice/mailroom/send_email.py", line 32, in notify_uploader
    send_email(

  File "/home/weiouyang/miniconda3/lib/python3.12/site-packages/bioimageio_collection_backoffice/mailroom/send_email.py", line 56, in send_email
    _ = smtp_server.login(BOT_EMAIL, settings.mail_password.get_secret_value())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/weiouyang/miniconda3/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception

  File "/home/weiouyang/miniconda3/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^

  File "/home/weiouyang/miniconda3/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)

smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 2adb3069b0e04-53d826af04dsm521678e87.273 - gsmtp')

```

**Comment by FynnBe** [comment]
It seems that the message was stored successfully anyway:
![image](https://github.com/user-attachments/assets/d14723f8-c920-452a-b27f-5ecaa49f91f7)

Just the timestamp is wrong.

Info for whomever will look at fixing this:
the next message:
![image](https://github.com/user-attachments/assets/667f36b5-79d2-49dd-849c-12c518f646d9)
was added by dispatching the `request_changes.yaml` workflow manually: https://github.com/bioimage-io/collection/actions/runs/11739016314/job/32702674041
