### ISSUE TITLE
Error when 'Requesting Changes'

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/bioimageio-uploader#104]
"Request changes" for https://bioimageio-uploader.netlify.app/#/status/resourceful-ant results in an error:
(possibly related to #103, also blocks 'requesting changes' anyway)

```console
                Traceback (most recent call last):

  File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 110, in wrapper
    data = await handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 314, in review
    review_data.save(backoffice)

  File "/home/weiouyang/workspace/hypha-app-engine/bioimageio-uploader-service/bioimageio_uploader_service/api.py", line 77, in save
    backoffice.request_changes(

  File "/home/weiouyang/miniconda3/lib/python3.12/site-packages/bioimageio_collection_backoffice/_backoffice.py", line 147, in request_changes
    notify_uploader(

  File "/home/weiouyang/miniconda3/lib/python3.12/site-packages/bioimageio_collection_backoffice/mailroom/send_email.py", line 23, in notify_uploader
    email, name = rv.get_uploader()
                  ^^^^^^^^^^^^^^^^^

  File "/home/weiouyang/miniconda3/lib/python3.12/site-packages/bioimageio_collection_backoffice/remote_collection.py", line 584, in get_uploader
    assert rdf_data is not None

AssertionError
```

**Comment by FynnBe** [comment]
FYI: the first comment came from my failed attempt reported above, the second comment (with the correct timestamp) comes from triggering https://github.com/bioimage-io/collection/actions/runs/11776187422 manually via github.com
![image](https://github.com/user-attachments/assets/6a02481d-6daa-4e4b-a4e1-d11359f7bc4d)
