### ISSUE TITLE
Uploader error after login

### ISSUE THREAD

**Issue by mese79** [bioimage-io/bioimageio-uploader#94]
Often I get an error after I log in to the uploader and I can not upload anything:
> Uploader service not found.

<img width="785" alt="Screenshot 2024-09-05 at 11 21 39" src="https://github.com/user-attachments/assets/26ba9a72-ef14-4459-a8e6-11bef09a1cca">

This is the console error log:  

```python
index-BbG8-eDU.js:24 TODO: Migrate animals and adjectives urls
(anonymous) @ index-BbG8-eDU.js:24
index-BbG8-eDU.js:64 Creating a new websocket connection to wss://hypha.aicell.io/ws
index-BbG8-eDU.js:41569 Query changed:  Object
index-BbG8-eDU.js:41569 Query changed:  Object
index-BbG8-eDU.js:64 WebSocket connection established
index-BbG8-eDU.js:64 Successfully connected to the server, workspace: ws-user-github|1878378, manager_id: ws-FQpYVy7B8b7zzKuC7tuf8Q
index-BbG8-eDU.js:70 Login info from Hypha:
index-BbG8-eDU.js:70 Object
index-BbG8-eDU.js:70 Error: RemoteError: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1128, in get_service
    raise exp
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1098, in get_service
    svc_info = await self.get_service_info(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 774, in get_service_info
    raise KeyError(f"Service not found: {service_id}@{app_id}")
KeyError: 'Service not found: ws-user-github|478667/*:bioimageio-uploader-service@*'
Exception: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1128, in get_service
    raise exp
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1098, in get_service
    svc_info = await self.get_service_info(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 774, in get_service_info
    raise KeyError(f"Service not found: {service_id}@{app_id}")
KeyError: 'Service not found: ws-user-github|478667/*:bioimageio-uploader-service@*'

    at G._decode (index-BbG8-eDU.js:61:20448)
    at G._decode (index-BbG8-eDU.js:62:1101)
    at G._handle_method (index-BbG8-eDU.js:61:15150)
    at G._fire (index-BbG8-eDU.js:62:8213)
    at G._on_message (index-BbG8-eDU.js:61:5199)
    at _websocket.onmessage (index-BbG8-eDU.js:64:4632)
connect_server @ index-BbG8-eDU.js:70
index-BbG8-eDU.js:70 Login info from Hypha:
index-BbG8-eDU.js:70 Object
index-BbG8-eDU.js:70 Error: RemoteError: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1128, in get_service
    raise exp
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1098, in get_service
    svc_info = await self.get_service_info(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 774, in get_service_info
    raise KeyError(f"Service not found: {service_id}@{app_id}")
KeyError: 'Service not found: ws-user-github|478667/*:bioimageio-uploader-service@*'
Exception: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1128, in get_service
    raise exp
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 1098, in get_service
    svc_info = await self.get_service_info(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha_rpc/utils/schema.py", line 401, in wrapper
    ret = await original_func(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/hypha/core/workspace.py", line 774, in get_service_info
    raise KeyError(f"Service not found: {service_id}@{app_id}")
KeyError: 'Service not found: ws-user-github|478667/*:bioimageio-uploader-service@*'

    at G._decode (index-BbG8-eDU.js:61:20448)
    at G._decode (index-BbG8-eDU.js:62:1101)
    at G._handle_method (index-BbG8-eDU.js:61:15150)
    at G._fire (index-BbG8-eDU.js:62:8213)
    at G._on_message (index-BbG8-eDU.js:61:5199)
    at _websocket.onmessage (index-BbG8-eDU.js:64:4632)
try_connect_server @ index-BbG8-eDU.js:70

```

**Comment by oeway** [comment]
Hi thanks for the report. The token was expired on the server side, I just restarted, please check if it works now. @mese79
